version: '3.1'
services:    
  minio:
    image: quay.io/minio/minio
    command:
    - server 
    - /data 
    - --console-address 
    - ":9001"
    ports:
    - 9000:9000
    - 9001:9001
    volumes:
    - ${PWD}/include/minio/data:/data
    env_file: .env
    extra_hosts:
    - "host.docker.internal:host-gateway"
  # metaflow-metadata-service:
  #   image: public.ecr.aws/outerbounds/metaflow_metadata_service:2.3.8
  #   environment:
  #     MF_METADATA_PORT: 8081
  #     MF_MIGRATION_PORT: 8082
  #   env_file: .env
  #   ports: 
  #   - 8081:8081
  #   - 8082:8082
  # metaflow-ui:
  #   image: mpgregor/metaflow-ui:latest
  #   #public.ecr.aws/outerbounds/metaflow_ui:1.3.1   #x86 only
  #   environment:
  #     PORT: 3000
  #   env_file: .env
  #   ports:
  #   - 3000:3000
  # metaflow-ui-backend:
  #   image: public.ecr.aws/outerbounds/metaflow_metadata_service:2.3.8
  #   command: 
  #     - /opt/latest/bin/python3
  #     - -m
  #     - services.ui_backend_service.ui_server
  #   environment:
  #     LOGLEVEL: "DEBUG"
  #   env_file: .env
  #   ports:
  #   - 8083:8083